In [50]:
import pandas as pd
data=pd.read_csv('HR_comma_sep.csv')

In [51]:
data

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  left  \
0                       157                   3              0     1   
1                       262                   6              0     1   
2                       272                   4              0     1   
3                       223                   5              0     1   
4                       159                   3              0     1   
...                     ...                 ...            ...   ...   
14994                   151                   3              0     1   
14995                   160                   3              0     1   
14996                   143                   3              0     1   
14997                   280                   4              0     1   
14998                   158                   3              0     1   

       promotion_last_5years    sales  salary  
0                          0    sales     low  
1                          0    sales  medium  
2                          0    sales  medium  
3                          0    sales     low  
4                          0    sales     low  
...                      ...      ...     ...  
14994                      0  support     low  
14995                      0  support     low  
14996                      0  support     low  
14997                      0  support     low  
14998                      0  support     low  

[14999 rows x 10 columns]

In [52]:
import numpy as np
np.corrcoef(data["number_project"], data["average_montly_hours"])

array([[1.        , 0.41721063],
       [0.41721063, 1.        ]])

In [53]:
from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(a,b) #Create a model and fit it
r_sq = model.score(a, b)
print('coefficient of determination:', r_sq)
print('intercept:', model.intercept_)
print('coef:', model.coef_)

coefficient of determination: 0.17406471345793328
intercept: [136.76027694]
coef: [[16.90485267]]


In [54]:
number_project=data["number_project"]

In [55]:
a=np.array(number_project).reshape(-1,1)

In [56]:
a

array([[2],
       [5],
       [7],
       ...,
       [2],
       [6],
       [2]], dtype=int64)

In [57]:
a=(np.array(data["number_project"]).reshape(-1,1)).shape

In [58]:
average_montly_hours=data["average_montly_hours"]

In [59]:
b=(np.array(data["average_montly_hours"]).reshape(-1,1))

In [60]:
b

array([[157],
       [262],
       [272],
       ...,
       [143],
       [280],
       [158]], dtype=int64)

array([[2790.82214662],
       [4565.8316773 ],
       [4734.88020403],
       ...,
       [2554.1542092 ],
       [4870.11902542],
       [2807.72699929]])

In [64]:
average_montly_hours = 16.90485267*number_project+136.76027694

In [66]:
average_montly_hours = 16.90485267*5+136.76027694

In [67]:
average_montly_hours

221.28454029